# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24bd91bd5927f1bdb85fd5e221678ef2b65091fc16c393cab4bf48de80bb560dc1c86f7c5df9051aa3826a7a79ff92d8b0f24bff5b282275677035f53e7d8c43

test:
  secret_key_base: 2f0406a0e747dfa6b6b70d5dd0f5860617431c54296262ae71f90b0f7bffe48496515f0a0ff52a882ef3439779cc090d35409190ae995281562342abbdd13d67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
